"""
Memory Evolution - Track pattern origin, versions, failures, fixes, and usage.

This component provides a complete evolutionary history for patterns:
- Origin tracking (source, session, consolidation)
- Version history with change reasons
- Failure and fix records
- Usage statistics over time
- Pattern lineage (ancestors and descendants)
- Evolution events (mutation, merge, split)

This implements the Epic requirement for memory evolution that enables
the system to understand how patterns came to be and how they evolved.
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional, Set, Tuple
import uuid
import json
import logging
from pathlib import Path

from rpa.core.graph import Node, PatternGraph
from rpa.memory.ltm import LongTermMemory, ConsolidationRecord
from rpa.closed_loop.outcome_evaluator import Outcome, OutcomeType
from rpa.closed_loop.pattern_mutator import MutationType

logger = logging.getLogger(__name__)


class EvolutionEvent(Enum):
    """Types of pattern evolution events."""
    CREATED = "created"               # Pattern was first created
    CONSOLIDATED = "consolidated"     # Moved from STM to LTM
    MUTATED = "mutated"               # Content changed via mutation
    FIXED = "fixed"                   # Fixed due to failure
    ENHANCED = "enhanced"             # Improved without failure
    GENERALIZED = "generalized"       # Made more abstract
    SPECIALIZED = "specialized"       # Made more specific
    DEPRECATED = "deprecated"         # Marked as obsolete
    RESTORED = "restored"             # Restored from deprecated
    MERGED = "merged"                 # Combined with another pattern
    SPLIT = "split"                   # Split into multiple patterns
    FORKED = "forked"                 # Created as a copy
    RETIRED = "retired"               # Removed from active use


class OriginType(Enum):
    """Source/origin of a pattern."""
    LEARNED = "learned"               # Learned from training data
    DERIVED = "derived"               # Derived from another pattern
    MUTATED = "mutated"               # Created via mutation
    MERGED = "merged"                 # Created by merging patterns
    USER_PROVIDED = "user_provided"   # Explicitly provided by user
    SYSTEM_GENERATED = "system"       # Generated by the system
    IMPORTED = "imported"             # Imported from external source


@dataclass
class PatternOrigin:
    """
    Tracks where a pattern came from.

    Every pattern has an origin that explains how it entered the system.
    """
    pattern_id: str
    origin_type: OriginType
    source: str = ""                  # Dataset name, session ID, etc.
    created_at: datetime = field(default_factory=datetime.now)
    created_by: str = ""              # Component or process that created it

    # If derived from another pattern
    parent_pattern_id: Optional[str] = None
    derivation_method: Optional[str] = None  # mutation, abstraction, etc.

    # Original context
    original_content: Optional[str] = None
    original_label: Optional[str] = None

    # Training context (if learned)
    dataset: Optional[str] = None
    sample_id: Optional[str] = None

    # Metadata
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "pattern_id": self.pattern_id,
            "origin_type": self.origin_type.value,
            "source": self.source,
            "created_at": self.created_at.isoformat(),
            "created_by": self.created_by,
            "parent_pattern_id": self.parent_pattern_id,
            "derivation_method": self.derivation_method,
            "original_content": self.original_content[:500] if self.original_content else None,
            "original_label": self.original_label,
            "dataset": self.dataset,
            "sample_id": self.sample_id,
            "metadata": self.metadata,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "PatternOrigin":
        """Create from dictionary."""
        return cls(
            pattern_id=data["pattern_id"],
            origin_type=OriginType(data["origin_type"]),
            source=data.get("source", ""),
            created_at=datetime.fromisoformat(data["created_at"]) if data.get("created_at") else datetime.now(),
            created_by=data.get("created_by", ""),
            parent_pattern_id=data.get("parent_pattern_id"),
            derivation_method=data.get("derivation_method"),
            original_content=data.get("original_content"),
            original_label=data.get("original_label"),
            dataset=data.get("dataset"),
            sample_id=data.get("sample_id"),
            metadata=data.get("metadata", {}),
        )


@dataclass
class VersionRecord:
    """
    Record of a pattern version change.

    Every time a pattern's content changes, a version record is created.
    """
    version_id: str
    pattern_id: str
    version_number: int
    timestamp: datetime = field(default_factory=datetime.now)

    # What changed
    event_type: EvolutionEvent = EvolutionEvent.MUTATED
    change_summary: str = ""

    # Content at this version
    content: str = ""
    label: str = ""

    # Delta from previous
    previous_version_id: Optional[str] = None
    content_delta: Optional[str] = None  # Diff or summary of changes

    # Trigger
    triggering_outcome_id: Optional[str] = None
    triggering_error: Optional[str] = None
    triggering_user: Optional[str] = None

    # Hash for quick comparison
    content_hash: str = ""

    # Active status
    is_active: bool = True
    deprecated_at: Optional[datetime] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "version_id": self.version_id,
            "pattern_id": self.pattern_id,
            "version_number": self.version_number,
            "timestamp": self.timestamp.isoformat(),
            "event_type": self.event_type.value,
            "change_summary": self.change_summary,
            "content": self.content[:500] if self.content else None,
            "label": self.label,
            "previous_version_id": self.previous_version_id,
            "content_delta": self.content_delta,
            "triggering_outcome_id": self.triggering_outcome_id,
            "triggering_error": self.triggering_error,
            "triggering_user": self.triggering_user,
            "content_hash": self.content_hash,
            "is_active": self.is_active,
            "deprecated_at": self.deprecated_at.isoformat() if self.deprecated_at else None,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "VersionRecord":
        """Create from dictionary."""
        return cls(
            version_id=data["version_id"],
            pattern_id=data["pattern_id"],
            version_number=data["version_number"],
            timestamp=datetime.fromisoformat(data["timestamp"]) if data.get("timestamp") else datetime.now(),
            event_type=EvolutionEvent(data.get("event_type", "mutated")),
            change_summary=data.get("change_summary", ""),
            content=data.get("content", ""),
            label=data.get("label", ""),
            previous_version_id=data.get("previous_version_id"),
            content_delta=data.get("content_delta"),
            triggering_outcome_id=data.get("triggering_outcome_id"),
            triggering_error=data.get("triggering_error"),
            triggering_user=data.get("triggering_user"),
            content_hash=data.get("content_hash", ""),
            is_active=data.get("is_active", True),
            deprecated_at=datetime.fromisoformat(data["deprecated_at"]) if data.get("deprecated_at") else None,
        )


@dataclass
class FailureRecord:
    """
    Record of a pattern failure.

    Tracks when and why a pattern failed, enabling failure analysis.
    """
    failure_id: str
    pattern_id: str
    version_id: str

    # Failure details
    timestamp: datetime = field(default_factory=datetime.now)
    error_type: str = ""
    error_message: str = ""
    error_category: str = ""  # syntax, runtime, logic, semantic

    # Context
    input_context: Optional[str] = None
    expected_output: Optional[str] = None
    actual_output: Optional[str] = None

    # Outcome reference
    outcome_id: Optional[str] = None
    outcome_type: Optional[str] = None

    # Fix status
    was_fixed: bool = False
    fix_version_id: Optional[str] = None
    fix_description: Optional[str] = None

    # Learning value
    learning_value: float = 0.0

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "failure_id": self.failure_id,
            "pattern_id": self.pattern_id,
            "version_id": self.version_id,
            "timestamp": self.timestamp.isoformat(),
            "error_type": self.error_type,
            "error_message": self.error_message[:500] if self.error_message else None,
            "error_category": self.error_category,
            "input_context": self.input_context[:200] if self.input_context else None,
            "expected_output": self.expected_output[:100] if self.expected_output else None,
            "actual_output": self.actual_output[:100] if self.actual_output else None,
            "outcome_id": self.outcome_id,
            "outcome_type": self.outcome_type,
            "was_fixed": self.was_fixed,
            "fix_version_id": self.fix_version_id,
            "fix_description": self.fix_description,
            "learning_value": self.learning_value,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "FailureRecord":
        """Create from dictionary."""
        return cls(
            failure_id=data["failure_id"],
            pattern_id=data["pattern_id"],
            version_id=data["version_id"],
            timestamp=datetime.fromisoformat(data["timestamp"]) if data.get("timestamp") else datetime.now(),
            error_type=data.get("error_type", ""),
            error_message=data.get("error_message", ""),
            error_category=data.get("error_category", ""),
            input_context=data.get("input_context"),
            expected_output=data.get("expected_output"),
            actual_output=data.get("actual_output"),
            outcome_id=data.get("outcome_id"),
            outcome_type=data.get("outcome_type"),
            was_fixed=data.get("was_fixed", False),
            fix_version_id=data.get("fix_version_id"),
            fix_description=data.get("fix_description"),
            learning_value=data.get("learning_value", 0.0),
        )


@dataclass
class UsageSnapshot:
    """
    Snapshot of pattern usage at a point in time.

    Enables tracking of usage trends over time.
    """
    snapshot_id: str
    pattern_id: str
    timestamp: datetime = field(default_factory=datetime.now)

    # Usage counts
    total_uses: int = 0
    successful_uses: int = 0
    failed_uses: int = 0

    # Success metrics
    success_rate: float = 0.0
    average_score: float = 0.0

    # Reinforcement state
    strength: float = 1.0
    current_streak: int = 0

    # Rank among similar patterns
    domain_rank: Optional[int] = None
    global_rank: Optional[int] = None

    def __post_init__(self):
        """Calculate derived metrics."""
        if self.total_uses > 0 and self.success_rate == 0.0:
            self.success_rate = self.successful_uses / self.total_uses
        if self.average_score == 0.0:
            self.average_score = self.success_rate

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "snapshot_id": self.snapshot_id,
            "pattern_id": self.pattern_id,
            "timestamp": self.timestamp.isoformat(),
            "total_uses": self.total_uses,
            "successful_uses": self.successful_uses,
            "failed_uses": self.failed_uses,
            "success_rate": self.success_rate,
            "average_score": self.average_score,
            "strength": self.strength,
            "current_streak": self.current_streak,
            "domain_rank": self.domain_rank,
            "global_rank": self.global_rank,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "UsageSnapshot":
        """Create from dictionary."""
        return cls(
            snapshot_id=data["snapshot_id"],
            pattern_id=data["pattern_id"],
            timestamp=datetime.fromisoformat(data["timestamp"]) if data.get("timestamp") else datetime.now(),
            total_uses=data.get("total_uses", 0),
            successful_uses=data.get("successful_uses", 0),
            failed_uses=data.get("failed_uses", 0),
            success_rate=data.get("success_rate", 0.0),
            average_score=data.get("average_score", 0.0),
            strength=data.get("strength", 1.0),
            current_streak=data.get("current_streak", 0),
            domain_rank=data.get("domain_rank"),
            global_rank=data.get("global_rank"),
        )


@dataclass
class PatternLineage:
    """
    Tracks the lineage/ancestry of a pattern.

    Enables understanding of how patterns evolved from others.
    """
    pattern_id: str

    # Ancestors (parents, grandparents, etc.)
    ancestors: List[str] = field(default_factory=list)  # [parent_id, grandparent_id, ...]
    ancestor_depth: int = 0  # How many generations back

    # Descendants
    descendants: List[str] = field(default_factory=list)  # Direct children
    descendant_count: int = 0

    # Siblings (patterns with same parent)
    siblings: List[str] = field(default_factory=list)

    # Related patterns (same origin source)
    related: List[str] = field(default_factory=list)

    # Evolution path (sequence of pattern_ids showing evolution)
    evolution_path: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "pattern_id": self.pattern_id,
            "ancestors": self.ancestors,
            "ancestor_depth": self.ancestor_depth,
            "descendants": self.descendants,
            "descendant_count": self.descendant_count,
            "siblings": self.siblings,
            "related": self.related,
            "evolution_path": self.evolution_path,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "PatternLineage":
        """Create from dictionary."""
        return cls(
            pattern_id=data["pattern_id"],
            ancestors=data.get("ancestors", []),
            ancestor_depth=data.get("ancestor_depth", 0),
            descendants=data.get("descendants", []),
            descendant_count=data.get("descendant_count", 0),
            siblings=data.get("siblings", []),
            related=data.get("related", []),
            evolution_path=data.get("evolution_path", []),
        )


class MemoryEvolution:
    """
    Tracks the complete evolutionary history of patterns.

    This component provides:
    - Origin tracking: Where did this pattern come from?
    - Version history: How has it changed over time?
    - Failure analysis: When and why did it fail?
    - Usage trends: How is it being used?
    - Lineage tracking: What is its ancestry?

    Example:
        evolution = MemoryEvolution(ltm)

        # Record pattern creation
        evolution.record_origin(
            pattern_id="pattern_123",
            origin_type=OriginType.LEARNED,
            source="mbpp_dataset",
            dataset="mbpp",
            sample_id="mbpp_001",
        )

        # Record a failure
        evolution.record_failure(
            pattern_id="pattern_123",
            error_type="TypeError",
            error_message="unsupported operand",
            outcome_id="outcome_456",
        )

        # Get evolution history
        history = evolution.get_evolution_history("pattern_123")
    """

    def __init__(self, ltm: Optional[LongTermMemory] = None):
        """
        Initialize MemoryEvolution.

        Args:
            ltm: Optional LongTermMemory instance for pattern access
        """
        self.ltm = ltm

        # Origin tracking
        self._origins: Dict[str, PatternOrigin] = {}

        # Version tracking
        self._versions: Dict[str, List[VersionRecord]] = {}  # pattern_id -> versions
        self._version_index: Dict[str, VersionRecord] = {}    # version_id -> record

        # Failure tracking
        self._failures: Dict[str, List[FailureRecord]] = {}   # pattern_id -> failures
        self._failure_index: Dict[str, FailureRecord] = {}    # failure_id -> record

        # Usage tracking
        self._usage_snapshots: Dict[str, List[UsageSnapshot]] = {}  # pattern_id -> snapshots

        # Lineage tracking
        self._lineages: Dict[str, PatternLineage] = {}

        # Parent-child relationships
        self._children: Dict[str, List[str]] = {}  # parent_id -> child_ids
        self._parents: Dict[str, str] = {}          # child_id -> parent_id

        # Statistics
        self._stats = {
            "total_patterns_tracked": 0,
            "total_versions": 0,
            "total_failures": 0,
            "total_fixes": 0,
            "by_origin_type": {t.value: 0 for t in OriginType},
            "by_evolution_event": {e.value: 0 for e in EvolutionEvent},
        }

        # Configuration
        self._max_snapshots_per_pattern = 100
        self._max_failures_per_pattern = 100

    # === Origin Tracking ===

    def record_origin(
        self,
        pattern_id: str,
        origin_type: OriginType,
        source: str = "",
        created_by: str = "",
        parent_pattern_id: Optional[str] = None,
        derivation_method: Optional[str] = None,
        original_content: Optional[str] = None,
        original_label: Optional[str] = None,
        dataset: Optional[str] = None,
        sample_id: Optional[str] = None,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> PatternOrigin:
        """
        Record the origin of a pattern.

        Args:
            pattern_id: The pattern being tracked
            origin_type: How the pattern originated
            source: Source identifier (dataset, session, etc.)
            created_by: Component that created it
            parent_pattern_id: Parent pattern if derived
            derivation_method: How it was derived
            original_content: Original content before derivation
            original_label: Original label
            dataset: Dataset name if learned
            sample_id: Sample ID in dataset
            metadata: Additional metadata

        Returns:
            The created PatternOrigin record
        """
        origin = PatternOrigin(
            pattern_id=pattern_id,
            origin_type=origin_type,
            source=source,
            created_by=created_by,
            parent_pattern_id=parent_pattern_id,
            derivation_method=derivation_method,
            original_content=original_content,
            original_label=original_label,
            dataset=dataset,
            sample_id=sample_id,
            metadata=metadata or {},
        )

        self._origins[pattern_id] = origin
        self._stats["total_patterns_tracked"] += 1
        self._stats["by_origin_type"][origin_type.value] += 1

        # Update lineage if has parent
        if parent_pattern_id:
            self._record_parent_child(parent_pattern_id, pattern_id)

        logger.debug(f"Recorded origin for {pattern_id}: {origin_type.value}")

        return origin

    def get_origin(self, pattern_id: str) -> Optional[PatternOrigin]:
        """Get the origin of a pattern."""
        return self._origins.get(pattern_id)

    # === Version Tracking ===

    def record_version(
        self,
        pattern_id: str,
        event_type: EvolutionEvent,
        content: str,
        label: str = "",
        change_summary: str = "",
        triggering_outcome_id: Optional[str] = None,
        triggering_error: Optional[str] = None,
        triggering_user: Optional[str] = None,
    ) -> VersionRecord:
        """
        Record a new version of a pattern.

        Args:
            pattern_id: The pattern being versioned
            event_type: What kind of evolution event
            content: The content at this version
            label: The label at this version
            change_summary: Description of changes
            triggering_outcome_id: Outcome that triggered this version
            triggering_error: Error that triggered this version
            triggering_user: User who triggered this version

        Returns:
            The created VersionRecord
        """
        # Get version number
        versions = self._versions.get(pattern_id, [])
        version_number = len(versions) + 1
        version_id = f"ver_{pattern_id}_{version_number}"

        # Get previous version
        previous_version_id = versions[-1].version_id if versions else None

        # Calculate content hash
        import hashlib
        content_hash = hashlib.md5(content.encode()).hexdigest()[:12]

        # Calculate delta if previous exists
        content_delta = None
        if previous_version_id and versions:
            prev_content = versions[-1].content
            if prev_content != content:
                content_delta = self._calculate_delta(prev_content, content)

        version = VersionRecord(
            version_id=version_id,
            pattern_id=pattern_id,
            version_number=version_number,
            event_type=event_type,
            content=content,
            label=label,
            change_summary=change_summary,
            previous_version_id=previous_version_id,
            content_delta=content_delta,
            triggering_outcome_id=triggering_outcome_id,
            triggering_error=triggering_error,
            triggering_user=triggering_user,
            content_hash=content_hash,
        )

        # Store
        if pattern_id not in self._versions:
            self._versions[pattern_id] = []
        self._versions[pattern_id].append(version)
        self._version_index[version_id] = version

        # Update stats
        self._stats["total_versions"] += 1
        self._stats["by_evolution_event"][event_type.value] += 1

        logger.debug(
            f"Recorded version {version_number} for {pattern_id}: {event_type.value}"
        )

        return version

    def get_versions(self, pattern_id: str) -> List[VersionRecord]:
        """Get all versions of a pattern."""
        return self._versions.get(pattern_id, [])

    def get_version(self, version_id: str) -> Optional[VersionRecord]:
        """Get a specific version."""
        return self._version_index.get(version_id)

    def get_current_version(self, pattern_id: str) -> Optional[VersionRecord]:
        """Get the current (latest) version of a pattern."""
        versions = self._versions.get(pattern_id, [])
        # Find the latest active version
        for v in reversed(versions):
            if v.is_active:
                return v
        return versions[-1] if versions else None

    # === Failure Tracking ===

    def record_failure(
        self,
        pattern_id: str,
        version_id: str,
        error_type: str,
        error_message: str,
        error_category: str = "",
        input_context: Optional[str] = None,
        expected_output: Optional[str] = None,
        actual_output: Optional[str] = None,
        outcome_id: Optional[str] = None,
        outcome_type: Optional[str] = None,
        learning_value: float = 0.0,
    ) -> FailureRecord:
        """
        Record a pattern failure.

        Args:
            pattern_id: The pattern that failed
            version_id: The version that failed
            error_type: Type of error (TypeError, ValueError, etc.)
            error_message: Full error message
            error_category: Category (syntax, runtime, logic, semantic)
            input_context: Input that caused the failure
            expected_output: What was expected
            actual_output: What was produced
            outcome_id: Associated outcome ID
            outcome_type: Type of outcome
            learning_value: How valuable for learning

        Returns:
            The created FailureRecord
        """
        failure_id = f"fail_{uuid.uuid4().hex[:8]}"

        failure = FailureRecord(
            failure_id=failure_id,
            pattern_id=pattern_id,
            version_id=version_id,
            error_type=error_type,
            error_message=error_message,
            error_category=error_category,
            input_context=input_context,
            expected_output=expected_output,
            actual_output=actual_output,
            outcome_id=outcome_id,
            outcome_type=outcome_type,
            learning_value=learning_value,
        )

        # Store
        if pattern_id not in self._failures:
            self._failures[pattern_id] = []
        self._failures[pattern_id].append(failure)
        self._failure_index[failure_id] = failure

        # Trim if needed
        if len(self._failures[pattern_id]) > self._max_failures_per_pattern:
            removed = self._failures[pattern_id].pop(0)
            del self._failure_index[removed.failure_id]

        self._stats["total_failures"] += 1

        logger.debug(f"Recorded failure for {pattern_id}: {error_type}")

        return failure

    def record_fix(
        self,
        failure_id: str,
        fix_version_id: str,
        fix_description: str,
    ) -> bool:
        """
        Record that a failure was fixed.

        Args:
            failure_id: The failure that was fixed
            fix_version_id: Version that fixes it
            fix_description: Description of the fix

        Returns:
            True if successful
        """
        failure = self._failure_index.get(failure_id)
        if not failure:
            return False

        failure.was_fixed = True
        failure.fix_version_id = fix_version_id
        failure.fix_description = fix_description

        self._stats["total_fixes"] += 1

        return True

    def get_failures(self, pattern_id: str) -> List[FailureRecord]:
        """Get all failures for a pattern."""
        return self._failures.get(pattern_id, [])

    def get_unfixed_failures(self, pattern_id: str) -> List[FailureRecord]:
        """Get unfixed failures for a pattern."""
        return [f for f in self._failures.get(pattern_id, []) if not f.was_fixed]

    # === Usage Tracking ===

    def record_usage_snapshot(
        self,
        pattern_id: str,
        total_uses: int,
        successful_uses: int,
        failed_uses: int,
        strength: float = 1.0,
        current_streak: int = 0,
        domain_rank: Optional[int] = None,
        global_rank: Optional[int] = None,
    ) -> UsageSnapshot:
        """
        Record a usage snapshot for a pattern.

        Args:
            pattern_id: The pattern
            total_uses: Total times used
            successful_uses: Times succeeded
            failed_uses: Times failed
            strength: Current pattern strength
            current_streak: Current success/failure streak
            domain_rank: Rank among domain patterns
            global_rank: Rank among all patterns

        Returns:
            The created UsageSnapshot
        """
        snapshot_id = f"snap_{uuid.uuid4().hex[:8]}"

        success_rate = successful_uses / total_uses if total_uses > 0 else 0.0
        average_score = success_rate  # Simplified

        snapshot = UsageSnapshot(
            snapshot_id=snapshot_id,
            pattern_id=pattern_id,
            total_uses=total_uses,
            successful_uses=successful_uses,
            failed_uses=failed_uses,
            success_rate=success_rate,
            average_score=average_score,
            strength=strength,
            current_streak=current_streak,
            domain_rank=domain_rank,
            global_rank=global_rank,
        )

        # Store
        if pattern_id not in self._usage_snapshots:
            self._usage_snapshots[pattern_id] = []
        self._usage_snapshots[pattern_id].append(snapshot)

        # Trim if needed
        if len(self._usage_snapshots[pattern_id]) > self._max_snapshots_per_pattern:
            self._usage_snapshots[pattern_id].pop(0)

        return snapshot

    def get_usage_history(self, pattern_id: str) -> List[UsageSnapshot]:
        """Get usage history for a pattern."""
        return self._usage_snapshots.get(pattern_id, [])

    def get_usage_trend(self, pattern_id: str) -> Dict[str, Any]:
        """
        Analyze usage trend for a pattern.

        Returns:
            Dictionary with trend analysis
        """
        snapshots = self._usage_snapshots.get(pattern_id, [])
        if len(snapshots) < 2:
            return {"trend": "insufficient_data", "snapshots": len(snapshots)}

        # Compare recent vs earlier
        recent = snapshots[-5:] if len(snapshots) >= 5 else snapshots[-2:]
        earlier = snapshots[:-5] if len(snapshots) >= 5 else snapshots[:-2]
        
        # Handle edge case where earlier might be empty
        if not earlier:
            earlier = snapshots[:1]  # Use first snapshot as baseline

        recent_avg = sum(s.success_rate for s in recent) / len(recent) if recent else 0.0
        earlier_avg = sum(s.success_rate for s in earlier) / len(earlier) if earlier else 0.0

        # Calculate strength trend
        recent_strength = sum(s.strength for s in recent) / len(recent) if recent else 1.0
        earlier_strength = sum(s.strength for s in earlier) / len(earlier) if earlier else 1.0

        # Determine trend
        if recent_avg > earlier_avg + 0.1:
            trend = "improving"
        elif recent_avg < earlier_avg - 0.1:
            trend = "declining"
        else:
            trend = "stable"

        return {
            "trend": trend,
            "recent_success_rate": recent_avg,
            "earlier_success_rate": earlier_avg,
            "recent_strength": recent_strength,
            "earlier_strength": earlier_strength,
            "strength_change": recent_strength - earlier_strength,
            "snapshots": len(snapshots),
        }

    # === Lineage Tracking ===

    def _record_parent_child(self, parent_id: str, child_id: str) -> None:
        """Record a parent-child relationship."""
        if parent_id not in self._children:
            self._children[parent_id] = []
        self._children[parent_id].append(child_id)
        self._parents[child_id] = parent_id

        # Update lineages
        self._update_lineage(parent_id)
        self._update_lineage(child_id)

    def _update_lineage(self, pattern_id: str) -> None:
        """Update lineage for a pattern."""
        if pattern_id in self._lineages:
            lineage = self._lineages[pattern_id]
        else:
            lineage = PatternLineage(pattern_id=pattern_id)

        # Get ancestors
        ancestors = []
        current = pattern_id
        depth = 0
        while current in self._parents:
            parent = self._parents[current]
            ancestors.append(parent)
            current = parent
            depth += 1

        lineage.ancestors = ancestors
        lineage.ancestor_depth = depth

        # Get descendants
        def get_descendants(pid: str) -> List[str]:
            result = []
            for child in self._children.get(pid, []):
                result.append(child)
                result.extend(get_descendants(child))
            return result

        lineage.descendants = get_descendants(pattern_id)
        lineage.descendant_count = len(lineage.descendants)

        # Get siblings
        parent = self._parents.get(pattern_id)
        if parent:
            siblings = [c for c in self._children.get(parent, []) if c != pattern_id]
            lineage.siblings = siblings

        # Build evolution path
        lineage.evolution_path = list(reversed(ancestors)) + [pattern_id]

        self._lineages[pattern_id] = lineage

    def get_lineage(self, pattern_id: str) -> Optional[PatternLineage]:
        """Get lineage for a pattern."""
        if pattern_id not in self._lineages:
            self._update_lineage(pattern_id)
        return self._lineages.get(pattern_id)

    def get_ancestors(self, pattern_id: str) -> List[str]:
        """Get ancestor pattern IDs."""
        lineage = self.get_lineage(pattern_id)
        return lineage.ancestors if lineage else []

    def get_descendants(self, pattern_id: str) -> List[str]:
        """Get descendant pattern IDs."""
        lineage = self.get_lineage(pattern_id)
        return lineage.descendants if lineage else []

    # === Evolution History ===

    def get_evolution_history(self, pattern_id: str) -> Dict[str, Any]:
        """
        Get complete evolution history for a pattern.

        Returns:
            Dictionary with all evolution data
        """
        return {
            "pattern_id": pattern_id,
            "origin": self.get_origin(pattern_id).to_dict() if self.get_origin(pattern_id) else None,
            "versions": [v.to_dict() for v in self.get_versions(pattern_id)],
            "failures": [f.to_dict() for f in self.get_failures(pattern_id)],
            "unfixed_failures": len(self.get_unfixed_failures(pattern_id)),
            "usage_trend": self.get_usage_trend(pattern_id),
            "lineage": self.get_lineage(pattern_id).to_dict() if self.get_lineage(pattern_id) else None,
        }

    def get_evolution_summary(self, pattern_id: str) -> Dict[str, Any]:
        """
        Get a concise summary of pattern evolution.

        Returns:
            Dictionary with key evolution metrics
        """
        versions = self.get_versions(pattern_id)
        failures = self.get_failures(pattern_id)
        origin = self.get_origin(pattern_id)
        lineage = self.get_lineage(pattern_id)

        return {
            "pattern_id": pattern_id,
            "origin_type": origin.origin_type.value if origin else "unknown",
            "source": origin.source if origin else "",
            "total_versions": len(versions),
            "current_version": versions[-1].version_number if versions else 0,
            "total_failures": len(failures),
            "fixed_failures": sum(1 for f in failures if f.was_fixed),
            "ancestor_depth": lineage.ancestor_depth if lineage else 0,
            "descendant_count": lineage.descendant_count if lineage else 0,
            "age_days": (datetime.now() - origin.created_at).days if origin else 0,
        }

    # === Pattern Analysis ===

    def find_patterns_by_origin(self, origin_type: OriginType) -> List[str]:
        """Find all patterns with a specific origin type."""
        return [
            pid for pid, origin in self._origins.items()
            if origin.origin_type == origin_type
        ]

    def find_patterns_by_source(self, source: str) -> List[str]:
        """Find all patterns from a specific source."""
        return [
            pid for pid, origin in self._origins.items()
            if origin.source == source
        ]

    def find_problematic_patterns(self, min_failures: int = 3) -> List[Dict[str, Any]]:
        """
        Find patterns with many failures.

        Returns:
            List of patterns with failure counts
        """
        problematic = []
        for pattern_id, failures in self._failures.items():
            unfixed = [f for f in failures if not f.was_fixed]
            if len(unfixed) >= min_failures:
                problematic.append({
                    "pattern_id": pattern_id,
                    "total_failures": len(failures),
                    "unfixed_failures": len(unfixed),
                    "common_error_types": list(set(f.error_type for f in unfixed)),
                })

        return sorted(problematic, key=lambda x: -x["unfixed_failures"])

    def find_stale_patterns(self, days: int = 30) -> List[Dict[str, Any]]:
        """
        Find patterns that haven't been updated recently.

        Returns:
            List of stale patterns
        """
        stale = []
        cutoff = datetime.now() - timedelta(days=days) if 'timedelta' in dir() else datetime.now()

        for pattern_id, versions in self._versions.items():
            if versions:
                last_version = versions[-1]
                if last_version.timestamp < cutoff:
                    stale.append({
                        "pattern_id": pattern_id,
                        "last_updated": last_version.timestamp.isoformat(),
                        "version": last_version.version_number,
                    })

        return stale

    def find_evolving_patterns(self) -> List[Dict[str, Any]]:
        """
        Find patterns that are actively evolving.

        Returns:
            List of actively evolving patterns
        """
        evolving = []
        for pattern_id, versions in self._versions.items():
            if len(versions) >= 3:
                # Check if recent versions are enhancements
                recent = versions[-3:]
                enhancements = sum(
                    1 for v in recent
                    if v.event_type in (EvolutionEvent.ENHANCED, EvolutionEvent.FIXED)
                )
                if enhancements >= 2:
                    evolving.append({
                        "pattern_id": pattern_id,
                        "total_versions": len(versions),
                        "recent_enhancements": enhancements,
                    })

        return sorted(evolving, key=lambda x: -x["total_versions"])

    # === Statistics ===

    def get_stats(self) -> Dict[str, Any]:
        """Get evolution statistics."""
        return {
            **self._stats,
            "patterns_with_versions": len(self._versions),
            "patterns_with_failures": len(self._failures),
            "patterns_with_usage_tracking": len(self._usage_snapshots),
            "lineages_tracked": len(self._lineages),
            "fix_rate": (
                self._stats["total_fixes"] / max(1, self._stats["total_failures"])
            ),
        }

    # === Delta Calculation ===

    def _calculate_delta(self, old_content: str, new_content: str) -> str:
        """Calculate a simple delta description."""
        old_lines = set(old_content.split("\n"))
        new_lines = set(new_content.split("\n"))

        added = new_lines - old_lines
        removed = old_lines - new_lines

        parts = []
        if added:
            parts.append(f"+{len(added)} lines")
        if removed:
            parts.append(f"-{len(removed)} lines")

        return " | ".join(parts) if parts else "content changed"

    # === Serialization ===

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to dictionary."""
        return {
            "origins": {pid: o.to_dict() for pid, o in self._origins.items()},
            "versions": {
                pid: [v.to_dict() for v in vers]
                for pid, vers in self._versions.items()
            },
            "failures": {
                pid: [f.to_dict() for f in fails]
                for pid, fails in self._failures.items()
            },
            "usage_snapshots": {
                pid: [s.to_dict() for s in snaps]
                for pid, snaps in self._usage_snapshots.items()
            },
            "lineages": {
                pid: l.to_dict() for pid, l in self._lineages.items()
            },
            "children": self._children,
            "parents": self._parents,
            "stats": self._stats,
        }

    def from_dict(self, data: Dict[str, Any]) -> None:
        """Deserialize from dictionary."""
        self._origins = {
            pid: PatternOrigin.from_dict(o)
            for pid, o in data.get("origins", {}).items()
        }

        self._versions = {}
        for pid, vers_data in data.get("versions", {}).items():
            self._versions[pid] = [VersionRecord.from_dict(v) for v in vers_data]
            for v in self._versions[pid]:
                self._version_index[v.version_id] = v

        self._failures = {}
        for pid, fails_data in data.get("failures", {}).items():
            self._failures[pid] = [FailureRecord.from_dict(f) for f in fails_data]
            for f in self._failures[pid]:
                self._failure_index[f.failure_id] = f

        self._usage_snapshots = {
            pid: [UsageSnapshot.from_dict(s) for s in snaps]
            for pid, snaps in data.get("usage_snapshots", {}).items()
        }

        self._lineages = {
            pid: PatternLineage.from_dict(l)
            for pid, l in data.get("lineages", {}).items()
        }

        self._children = data.get("children", {})
        self._parents = data.get("parents", {})
        self._stats = data.get("stats", self._stats)


# Import timedelta for find_stale_patterns
from datetime import timedelta
